### ISSUE TITLE
How to add the offset of mpu6050?

### ISSUE THREAD

**Issue by schosdas** [zhiyong9654/multiple_MPU6050#1]
Hello

As in this example, I want to connect several mpu6050 and output the angle of each sensor.
In this example, the offset with the sensor calibration is missing, so can I know how to add this function?
And you excluded the interrupt pin connection, so is there any problem with calculating the angular values of the sensors?

Thank you.

**Comment by zhiyong9654** [comment]
Hey, under the init function there's a [line ](https://github.com/zhiyong9654/multiple_MPU6050/blob/ac7f8b1ebdf5f570b04af0856b1d4b0312d1ed9c/gyro_class.ino#L44)for the MPU to be initialized. This uses Jeff Rowberg's script as i mentioned. This line does the sensor calibration.

As for the interrupt pin, it's purpose is for the MPU to come out of 'sleep mode' afaik. So there isn't an impact on readings.
